# Generated by Django 5.0.6 on 2024-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cm_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="batch",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="location",
            field=models.CharField(default="India", max_length=255),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
